### ISSUE TITLE
Order Songs within playlist

### ISSUE THREAD

**Issue by tommibru** [linsomniac/spotify_to_ytmusic#28] opened 2024-02-06 22:59 UTC
I was able to use the software via command line and with the version 0.9.12.

One thing I was wondering about is i noticed when it creates a copy of a playlist the songs in the new YT playlist are backwards in the order, meaning the latest song that was added is now the first on the playlist. 

Would you know if there is a way to reverse that? 

Tommi

**Comment by linsomniac** [comment] 2024-02-07 03:47
I thought that was resolved in 0.9.12: when the playlist is loaded it is first reversed.  This is because it starts with the first song in the Spotify list, but adds it to the YTMusic playlist by putting it in the front, so without the reverse it ends up in reversed order.

There isn't an option currently to turn that off, I can look into that, but Yoween did write a "reverse_playlist.py" script that you can find in this repo, that will reverse the Spotify playlist file, and then you can load it and try again.

**Comment by tommibru** [comment] 2024-02-07 04:47
i did find the revision, looks. like it was addressed in 0.9.11 i cannot find the" reverse_playlist.py" though.

but to be honest even if I do find it I probably wont know how to implement it within the latest version.

Thanks

**Comment by linsomniac** [comment] 2024-02-07 14:58
Sorry, the "reverse_playlist.py" is only in the more recent versions, you can download it directly here: https://raw.githubusercontent.com/linsomniac/spotify_to_ytmusic/main/reverse_playlist.py

Just run it and it'll give you help on using it.  I believe the usage would be "python3 reverse_playlist.py -r playlists.json"

**Comment by ACodeGerm** [comment] 2024-02-08 17:13
Ran into the same issue today! Playlists are not reversed. Running the reverse_playlist.py fixed it!

**Comment by shadvey** [comment] 2024-02-11 23:54
i am new to python i am trying to run the exe it simply dissappers after openning for a few seconds and when i try to put the code to the cmd it simply says python is not found when i actually use the graphical gui and i have the python installed on my pc with the correct path do i need to wait for an update?

**Comment by Yoween** [comment] 2024-02-12 00:18
> Ran into the same issue today! Playlists are not reversed. Running the reverse_playlist.py fixed it!

I found why this happened. The function to copy liked songs works differently from the other playlist and I didn't use the thing that reverse your liked songs. Fixing this tomorrow.

**Comment by Yoween** [comment] 2024-02-12 00:21
> i am new to python i am trying to run the exe it simply dissappers after openning for a few seconds and when i try to put the code to the cmd it simply says python is not found when i actually use the graphical gui and i have the python installed on my pc with the correct path do i need to wait for an update?

I don't remember this project having any .exe file... Are you sure you downloaded the right project? And can you be more explicit about what error you get please (screenshot/copy-paste)

**Comment by shadvey** [comment] 2024-02-12 01:30
> > i am new to python i am trying to run the exe it simply dissappers after openning for a few seconds and when i try to put the code to the cmd it simply says python is not found when i actually use the graphical gui and i have the python installed on my pc with the correct path do i need to wait for an update?
> 
> I don't remember this project having any .exe file... Are you sure you downloaded the right project? And can you be more explicit about what error you get please (screenshot/copy-paste)

Sorry i meant .py not exe i am talking about the reverse_playlist.

**Comment by Yoween** [comment] 2024-02-12 10:56
> > > i am new to python i am trying to run the exe it simply dissappers after openning for a few seconds and when i try to put the code to the cmd it simply says python is not found when i actually use the graphical gui and i have the python installed on my pc with the correct path do i need to wait for an update?
> > 
> > 
> > I don't remember this project having any .exe file... Are you sure you downloaded the right project? And can you be more explicit about what error you get please (screenshot/copy-paste)
> 
> Sorry i meant .py not exe i am talking about the reverse_playlist.

Okay, that's fine. But I still need more elements to work with. Please provide a screenshot of the error and the steps to reproduce it.

**Comment by Yoween** [comment] 2024-02-12 13:15
> Ran into the same issue today! Playlists are not reversed. Running the reverse_playlist.py fixed it!

OH I UNDERSTAND NOW. I checked the code and it works the same way for every playlists, including liked songs. BUT, when adding a music to liked songs, it adds it from bottom to top, so the last one is at the top of the liked songs playlists. HOWEVER, with regular playlists, it adds from top to bottom, meaning the last added song it at the VERY BOTTOM of it !! It seems to be working with my reverse_playlist.py and while it makes little to no sense, I'll see with @linsomniac on how to implement this.

**Comment by linsomniac** [comment] 2024-02-12 15:39
@Yoween Does this mean that we need to reverse normal playlists but not liked songs?

**Comment by Yoween** [comment] 2024-02-12 15:45
> @Yoween Does this mean that we need to reverse normal playlists but not liked songs?

I think so, that's what I did in my latest commit. So far it seems to be working fine

**Comment by linsomniac** [comment] 2024-02-12 16:02
I just implemented "reverse_playlist" arguments for the backend "copy_playlists()", "copy_all_playlists()", and "iter_spotify_playlist()".  In the CLI, I added some "--reverse-playlist" and "--no-reverse_playlist" CLI arguments reflecting the liked songs are not reversed (so the user can add --reverse-playlist to reverse them) and the other playlists are normally reversed when loading (so the user can add --no-reverse-playlist to flip that).

Does that sound about right?

**Closed by linsomniac** 2024-02-12 16:02 UTC

**Comment by Yoween** [comment] 2024-02-12 22:32
> I just implemented "reverse_playlist" arguments for the backend "copy_playlists()", "copy_all_playlists()", and "iter_spotify_playlist()". In the CLI, I added some "--reverse-playlist" and "--no-reverse_playlist" CLI arguments reflecting the liked songs are not reversed (so the user can add --reverse-playlist to reverse them) and the other playlists are normally reversed when loading (so the user can add --no-reverse-playlist to flip that).
> 
> Does that sound about right?

Okay, I fixed my previous mistakes in the latest commits, but since I changed some stuff you may need to change the code a bit again when implementing this.
